project:
  type: website
  output-dir: docs
  resources:
    - "*.jpg"
    - "*.png"
    - "*.pdf"

website:
  title: "Regan Smock"
  description: "Regan Smock - PhD Candidate in Sociology at the University of Iowa"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
     # - href: smock_CV.pdf
     #   text: CV

format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    




