project:
  type: website
  output-dir: docs

website:
  title: "Regan Smock"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Research.qmd
        text: Research

format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    




